feat: send message queen (git clone + webdownload, based on pr22)
openmerlin/gitea pull request #26
Opened 2024-01-29 11:40 UTC by AaronMKk

Please check the following:
1. Make sure you are targeting the `main` branch, pull requests on release branches are only allowed for backports.
2. Make sure you have read contributing guidelines: https://github.com/go-gitea/gitea/blob/main/CONTRIBUTING.md .
3. Describe what your pull request does and which issue you're targeting (if any).
4. It is recommended to enable "Allow edits by maintainers", so maintainers can help more easily.
5. Your input here will be included in the commit message when this PR has been merged. If you don't want some content to be included, please separate them with a line like `---`.
6. Delete all these tips before posting.

2024-01-30 08:08 UTC, pkking commented on event/sender.go
> +		RepoUserEmail: ctx.ContextUser.Email,
这里为什么不用 ctx.Repo.Repository.Owner.Email

2024-01-30 08:19 UTC, AaronMKk commented on event/sender.go
> +		RepoUserEmail: ctx.ContextUser.Email,
已修改

2024-01-30 08:19 UTC, AaronMKk commented on event/sender.go
> +	"code.gitea.io/gitea/event/infrastructure/kafka"
已修改

2024-01-30 08:22 UTC, pkking commented on event/sender.go
> +	"github.com/google/uuid"
import 顺序按照 标准库，第三方库，内部库顺序，因此：
```
  "strconv"
	"time"

  "github.com/google/uuid"
	"github.com/sirupsen/logrus"

	"code.gitea.io/gitea/modules/context"
	"code.gitea.io/gitea/event/infrastructure/kafka"
```

2024-01-30 08:23 UTC, AaronMKk commented on event/sender.go
> +	"github.com/google/uuid"
已修改

2024-01-31 02:49 UTC, zengchen1024 requested changes

2024-01-31 02:49 UTC, zengchen1024 commented on routers/web/githttp.go
> +	}, ignSignInAndCsrf, requireSignIn, repo.HTTPGitEnabledHandler, context.RepoAssignment, repo.CorsHandler(), context_service.UserAssignmentWeb())
context.RepoAssignment 这个起什么作用

2024-01-31 02:49 UTC, zengchen1024 commented on routers/web/web.go
> +	chi_middleware "github.com/go-chi/chi/v5/middleware"
还原到53行

2024-01-31 02:49 UTC, zengchen1024 commented on routers/web/middleware/statistic.go
> +		log.Fatal("internal error of kafka sender: %s", err.Error())
用Fatal不大合适吧

2024-01-31 02:49 UTC, zengchen1024 commented on routers/web/middleware/statistic.go
> +		log.Fatal("internal error of kafka sender: %s", err.Error())
同上

2024-01-31 02:49 UTC, zengchen1024 commented on routers/web/middleware/statistic.go
> +package middleware
建议这个目录改名为stat-middleware。package名为statmiddleware。

2024-01-31 02:49 UTC, zengchen1024 commented on modules/setting/message_queen.go
> +var MQ = struct {
参考storage的实现方式。声明一个配置的struct

2024-01-31 02:49 UTC, zengchen1024 commented on event/sender.go
> +type Detail struct {
type msgDetail struct

2024-01-31 02:49 UTC, zengchen1024 commented on modules/messagequeen/messagequeen.go
> +var messageMap = map[MessageType]NewMessageFunc{}
没必要这么复杂，因为当前只有kafka一种MQ。

2024-01-31 02:49 UTC, zengchen1024 commented on event/infrastructure/kafka/impl.go
> +package kafka
将这两个文件挪到modules下的messageaqueue

2024-01-31 02:49 UTC, zengchen1024 commented on modules/messagequeen/messagequeen.go
> +package messagequeen
typo queue not queen

2024-01-31 07:12 UTC, zengchen1024 requested changes

2024-01-31 07:12 UTC, zengchen1024 commented on routers/web/githttp.go
> +		}, context.RepoAssignment)
check一下运行顺序

2024-01-31 07:12 UTC, zengchen1024 commented on modules/setting/message_queue.go
> +	TopicName     string `ini:"TOPIC_NAME" json:",omitempty"`
避免锯齿形的变量声明

2024-01-31 07:12 UTC, zengchen1024 commented on modules/messagequeen/sender.go
> +	typGitClone    = "gitClone"
gitClone

2024-01-31 07:12 UTC, zengchen1024 commented on modules/messagequeen/sender.go
> +	log.Info("Publishing Git clone message: %#v\n", msg)
去掉日志

2024-01-31 07:12 UTC, zengchen1024 commented on modules/messagequeen/messagequeue .go
> +type MQConfig struct {
删除

2024-01-31 07:12 UTC, zengchen1024 commented on modules/messagequeen/messagequeue .go
> +type NewMessageFunc func(cfg MQConfig) error
删除

2024-01-31 07:12 UTC, zengchen1024 commented on modules/messagequeen/messagequeue .go
> +	err = NewMessage(MQConfig(setting.MQ))
return NewMessage(MQConfig(setting.MQ))

2024-01-31 07:12 UTC, zengchen1024 commented on modules/messagequeen/messagequeue .go
> +func NewMessage(cfg MQConfig) error {
删除

2024-01-31 07:12 UTC, zengchen1024 commented on modules/messagequeen/kafka.go
> +func retriveConfig(cfg MQConfig) Config {
func retriveConfig(cfg MQConfig) kfklib.Config {

2024-01-31 07:46 UTC, merged