fetch model upload method
openmerlin/gitea pull request #62
Opened 2024-04-08 13:52 UTC by AaronMKk

2024-04-09 02:49 UTC, TommyLike reviewed
整体上 日志输出比较少，需要补充。

2024-04-09 02:49 UTC, TommyLike commented on routers/api/v1/repo/file.go
> +	if apiOpts.BranchName == "" {
这个可以设置为强制指定吗？ 预留默认值的原因是啥？

2024-04-09 02:49 UTC, TommyLike commented on services/repository/files/preUpload.go
> +	if err := repo.MustNotBeArchived(); err != nil {
这个在外围注册的时候是不是已经校验过了

2024-04-09 02:49 UTC, TommyLike commented on services/repository/files/preUpload.go
> +		CachedOnly: false,
cacheonly 设置为false的原因是啥？

2024-04-09 02:49 UTC, TommyLike commented on routers/api/v1/repo/file.go
> +	for _, file := range apiOpts.Files {
需要对一次能够指定的文件数做限制。

2024-04-09 02:49 UTC, TommyLike commented on modules/structs/repo_file.go
> +	Size int64  `json:"size"`
size 是不是也要必须指定？

2024-04-09 09:51 UTC, zengchen1024 requested changes

2024-04-09 09:51 UTC, zengchen1024 commented on modules/structs/repo_file.go
> +	Files []*PreUploadFiles `json:"files" binding:"Required"`
Files []PreUploadFiles。 不要用指针

2024-04-09 09:51 UTC, zengchen1024 commented on modules/structs/repo_file.go
> +	Files []*ContentsResponse `json:"files"`
slice的成员不要用指针

2024-04-09 09:51 UTC, zengchen1024 commented on routers/api/v1/api.go
> +				m.Get("/preUpload", reqToken(), bind(api.PreUploadFileOptions{}), reqRepoBranchWriter, mustNotBeArchived, repo.FetchUploadModes)
请解释一下这些中间件的各自作用，从字面上看，mustNotBeArchived 就不应该用到

2024-04-09 09:51 UTC, zengchen1024 commented on modules/structs/repo_file.go
> +type PreUploadFiles struct {
s/PreUploadFiles/PreUploadFileInfo

2024-04-09 09:51 UTC, zengchen1024 commented on modules/structs/repo_file.go
> +	SHA  string `json:"sha"  binding:"Required"`
变量对齐，由短到长

2024-04-09 09:51 UTC, zengchen1024 commented on modules/structs/repo_file.go
> +type PreUploadFileOptions struct {
s/PreUploadFileOptions/PreUploadFilesOption

2024-04-09 09:51 UTC, zengchen1024 commented on services/repository/files/preUpload.go
> +	Files  []*PreUploadFile
不要用指针

2024-04-09 09:51 UTC, zengchen1024 commented on services/repository/files/preUpload.go
> +	"context"
包的声明格式不对，注意顺序

2024-04-09 09:51 UTC, zengchen1024 commented on routers/api/v1/repo/file.go
> +func fetchModes(ctx *context.APIContext, opts *files_service.PreUploadFileInf) (*api.PreUploadFilesResponse, error) {
感觉这函数封装的没有意义，建议直接使用files_service.FetchFileType

2024-04-09 09:51 UTC, zengchen1024 commented on services/repository/files/file.go
> +				Type: "lfs",
"lfs", "regular" 请定义常量

2024-04-09 09:51 UTC, zengchen1024 commented on services/repository/files/file.go
> +		if info, exists := attributeMap[file.TreePath]; (exists && info["filter"] == "lfs") || (file.Size > 5*1024*1024) {
5*1024*1024 定义配置文件

这里可以先判定大小，再check attributeMap，提高效率

2024-04-09 09:51 UTC, zengchen1024 commented on services/repository/files/preUpload.go
> +		if !git.IsErrBranchNotExist(err) || !repo.IsEmpty {
这个if 语句为true的情况是：branch存在 或者 仓库非空。这两种情况要返回错误，跟你的注释相违背。我理解这里要返回错误的情况应该是：branch不存在 或者 仓库为空， if git.IsErrBranchNotExist(err) || repo.IsEmpty

2024-04-09 09:51 UTC, zengchen1024 commented on services/repository/files/preUpload.go
> +	return preUploadFilesResponse, nil
55~60 可以直接替换为 return LFSOrRegularFile(tempUploadRepo, opts)

2024-04-09 09:51 UTC, zengchen1024 commented on services/repository/files/preUpload.go
> +	filesResponse, err := GetPreUploadFileResponse(attributes, infos.Files)
return GetPreUploadFileResponse(attributes, infos.Files)

2024-04-09 09:51 UTC, zengchen1024 commented on services/repository/files/temp_repo.go
> +func (t *TemporaryUploadRepository) FullyClone(branch string) error {
gitea原生的代码没有clone的实现吗，为啥还需要再实现一个clone。请说明一下背景

2024-04-09 12:06 UTC, pkking commented on routers/api/v1/repo/file.go
> +		log.Error("fail to fetching the type of the preUpload file %v", err)
这里不需要ctx.Error返回错误响应吗

2024-04-10 01:28 UTC, AaronMKk commented on routers/api/v1/repo/file.go
> +		log.Error("fail to fetching the type of the preUpload file %v", err)
已修改

2024-04-10 01:47 UTC, merged